### ISSUE TITLE
Accuracy is 0 when training?

### ISSUE THREAD

**Issue by FelixZhang7** [dmonterom/face_recognition_TF2#2]
`Epoch 1, Step 10, Loss: 62.92216, Reg loss: 16.30484, Accuracy: 0.00000, Reg coef: 1.00000
Epoch 1, Step 20, Loss: 69.79987, Reg loss: 16.31502, Accuracy: 0.00000, Reg coef: 1.00000
Epoch 1, Step 30, Loss: 54.62340, Reg loss: 16.32216, Accuracy: 0.00000, Reg coef: 1.00000
Epoch 1, Step 40, Loss: 62.94989, Reg loss: 16.32695, Accuracy: 0.00000, Reg coef: 1.00000
`

**Comment by dmonterom** [comment]
You need to wait for more iterations.
